apiVersion: v1
entries:
  aikit:
  - apiVersion: v2
    appVersion: v0.18.2
    created: "2025-08-07T18:12:31.798703628Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: dd1661af59d92bfcad8e78f38b5d92f650676ea2a84d740545382c6515ee1cd4
    name: aikit
    type: application
    urls:
    - https://kaito-project.github.io/aikit/charts/aikit-0.18.2.tgz
    version: 0.18.2
  - apiVersion: v2
    appVersion: v0.18.1
    created: "2025-08-07T02:19:16.595343812Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 5c882165cfd37a5adfed61c41fa1a5a392e7c4087f4632b6b8441668ed6af2f9
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.18.1.tgz
    version: 0.18.1
  - apiVersion: v2
    appVersion: v0.18.0
    created: "2025-02-26T06:24:46.8323747Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: e92bb448e33849415dbb749b3156d0c45d2cef43da7dfd92261893bcd8323703
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.18.0.tgz
    version: 0.18.0
  - apiVersion: v2
    appVersion: v0.17.0
    created: "2025-02-22T06:25:00.130470603Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 48bfd2364908a75807f459d4e4d29a46baa233787d4c823cab8d1691745ff4b1
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.17.0.tgz
    version: 0.17.0
  - apiVersion: v2
    appVersion: v0.16.0
    created: "2024-12-10T07:09:45.592400592Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 350f19f11f3eb7aadbba2cfb098b4ecd7f7762ac2b5d08526269ac3a3c4fa487
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.16.0.tgz
    version: 0.16.0
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2024-11-27T07:39:43.92514674Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 1263c90d662c4e1f8bb949456c914c155bdd0dab59f879baa304961e536176f9
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.15.0.tgz
    version: 0.15.0
  - apiVersion: v2
    appVersion: v0.14.0
    created: "2024-09-27T03:50:55.960196399Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 907f7526c41dc838f65add6505b87cb3fc59c37e5a343eff7ac2fc0d20a4a531
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.14.0.tgz
    version: 0.14.0
  - apiVersion: v2
    appVersion: v0.13.0
    created: "2024-09-07T20:35:46.368685834Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 6a7292acff812028b9d8b5cf6c9ead82a460bf88bd31b266ef217940e962b312
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.13.0.tgz
    version: 0.13.0
  - apiVersion: v2
    appVersion: v0.12.2
    created: "2024-08-03T23:18:45.737502414Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 2b874c24a073db76b68522e763f0ba6599c28a8c791207ecbed51832a9008730
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: v0.12.1
    created: "2024-08-03T20:26:38.580285414Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: 0f5f896fa6524cc2afc7957687bfd42b891dde8f706ad68ba6dd05b584503339
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.12.1.tgz
    version: 0.12.1
  - apiVersion: v2
    appVersion: v0.12.0
    created: "2024-07-28T05:56:06.460424523Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: cac8e549c9682179dc4145d43d2e3d4d00ffe5c5d51148b8501a0c99e9639047
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.12.0.tgz
    version: 0.12.0
  - apiVersion: v2
    appVersion: v0.11.2
    created: "2024-07-28T05:45:50.303453249Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: d5f4468c6ff7f1a3255378c88a049eab13d4e182b6a96979f0b8a312b6f99f93
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: v0.11.1
    created: "2024-06-13T05:44:20.458373774Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: fe5fc0b11a20f6c9d4688000cabb155147d8e9e29c2b4b3c16ff37a277970c04
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: v0.11.0
    created: "2024-06-13T03:49:04.209630378Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: d2f5c8786430045687f81ddcb8628eb55bd33ae910cba1be743d0d01e4ed3c39
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: v0.10.0
    created: "2024-06-06T11:11:44.855353505Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: cca85f5cd3a4ff216a78c1d87e92e94feefd1007157e76ed2ffd34aa92ca005c
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2024-05-30T21:53:53.832206301Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: bc1ea7f1a093bea613dd7cf792ce919794001492cd4fcf03c30c5e177f2f40c9
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.9.0.tgz
    version: 0.9.0
generated: "2025-08-07T18:12:31.798018743Z"
