{{- if not .Values.leaderWorkerSet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aikit.fullname" . }}
  labels:
    {{- include "aikit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "aikit.selectorLabels" . | nindent 4 }}
{{- end }}
